checks:
  - cmd: flake8
    name: 'Checking code quality'
  - cmd: 'pytest tests/'
    name: 'Running tests'
deploy: HEROKU
deploy_options:
  staging:
    dns: shizuoka-60622.herokussl.com
    heroku_app: releng-staging-tooltool
    heroku_dyno_type: web
    url: https://tooltool.staging.mozilla-releng.net
  testing:
    dns: shizuoka-60622.herokussl.com
    heroku_app: releng-testing-tooltool
    heroku_dyno_type: web
    url: https://tooltool.testing.mozilla-releng.net
  # (garbas): commeted out for the period when i'm on parental leave
  #production:
  #  dns: kochi-11433.herokussl.com,
  #  heroku_app: releng-production-tooltool,
  #  heroku_dyno_type: web,
  #  url: https://tooltool.mozilla-releng.net,
requires:
  - postgresql
run: FLASK
run_options:
  port: 8002
