---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Code Coverage"
consumes:
  - application/json
produces:
  - application/json
paths:
  /coverage/file:
    get:
      operationId: "shipit_code_coverage_backend.api.coverage_for_file"
      parameters:
      - name: changeset
        in: query
        description: Changeset
        required: true
        type: string
      - name: path
        in: query
        description: File
        required: true
        type: string
      responses:
        200:
          description: Code coverage information for a given file at a given changeset

  /coverage/changeset/{changeset}:
    get:
      operationId: "shipit_code_coverage_backend.api.coverage_by_changeset"
      parameters:
      - name: changeset
        in: path
        description: Changeset
        required: true
        type: string
      responses:
        200:
          description: Code coverage information by changeset

  /coverage/changeset_summary/{changeset}:
    get:
      operationId: "shipit_code_coverage_backend.api.coverage_summary_by_changeset"
      parameters:
      - name: changeset
        in: path
        description: Changeset
        required: true
        type: string
      responses:
        200:
          description: Code coverage summary by changeset

  /coverage/supported_extensions:
    get:
      operationId: "shipit_code_coverage_backend.api.coverage_supported_extensions"
      responses:
        200:
          description: File extensions supported for code coverage

  /coverage/latest:
    get:
      operationId: "shipit_code_coverage_backend.api.coverage_latest"
      responses:
        200:
          description: Latest coverage builds
