version: 0
allowPullRequests: public
metadata:
  name: "Mozilla RelEng"
  description: "Mozilla RelEng Services"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:

  - metadata:
      name: "0. Decidion task"
      description: ""
      owner: "{{ event.head.user.email }}"
      source: "https://github.com/mozilla-releng/services/tree/taskcluster-rework"
    scopes:
      - secrets:get:repo:github.com/mozilla-releng/services:branch:staging
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
        branches:
          - taskcluster-rework
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 7200  # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      features:
        taskclusterProxy: true
      env:
        TASKCLUSTER_SECRETS: "taskcluster/secrets/v1/secret/repo:github.com/mozilla-releng/services:branch:staging"
      command:
        - "/bin/bash"
        - "-c"
        - "mkdir /app && cd /app && wget https://github.com/mozilla-releng/services/archive/$GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd services-$GITHUB_HEAD_SHA && env && ./please configure-taskcluster --taskcluster-secrets $TASKCLUSTER_SECRETS"
