version: 0
allowPullRequests: public
metadata:
  name: "Mozilla RelEng"
  description: "Mozilla RelEng Services"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:

  - metadata:
      name: "setup"
      description: ""
      owner: "{{ event.head.user.email }}"
      source: "https://github.com/mozilla-releng/services/tree/taskcluster-rework"
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
        branches:
          - taskcluster-rework
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 7200  # seconds (i.e. two hours)
      image: "nixos/nix:latest"
      features:
        taskclusterProxy: true
      env:
        TASKCLUSTER_SECRETS: "taskcluster/secrets/v1/secre{

    "provisionerId": "aws-provisioner-v1",
    "workerType": "releng-task",
    "schedulerId": "-",
    "taskGroupId": "ReH4w-4NTtmjKfUVwi666A",
    "dependencies": [ ],
    "requires": "all-completed",
    "routes": [ ],
    "priority": "normal",
    "retries": 0,
    "created": "2017-01-05T17:08:51.217Z",
    "deadline": "2017-01-05T18:08:51.217Z",
    "expires": "2017-01-12T15:57:23.344Z",
    "scopes": [
        "queue:create-task:aws-provisioner-v1/releng-task"
    ],
    "payload": {
        "image": "tutum/curl",
        "command": [
            "/bin/bash",
            "-c",
            "curl -L https://github.com/taskcluster/slugid-go/releases/download/v1.0.0/slug-linux-amd64 > slugid && chmod +x ./slugid && apt-get update && apt-get install jq && curl -X PUT -d \"`curl -sL https://gist.githubusercontent.com/garbas/703275d089ba3539fed51cfcbff8ef81/raw/9bb921bc11be0cb0c623332de28663a67acf3ade/gista-file | sed \"s|TASK_ID|\\`echo $TASK_ID\\`|\" | sed \"s|CREATED|\\`date +%Y-%m-%dT%T.%sZ\\`|\" | sed \"s|DEADLINE|\\`date --set=\"+1 day\" +%Y-%m-%dT%T.%sZ\\`|\" | sed \"s|EXPIRES|\\`date --set=\"+1 year\" +%Y-%m-%dT%T.%sZ\\`|\"`\" http://taskcluster/queue/v1/task/`./slugid`"
        ],
        "features": {
            "taskclusterProxy": true
        },
        "maxRunTime": 10800
    },
    "metadata": {
        "name": "Example Task",
        "description": "Markdown description of **what** this task does",
        "owner": "name@example.com",
        "source": "https://tools.taskcluster.net/task-creator/"
    },
    "tags": { },
    "extra": { }

}t/repo:github.com/mozilla-releng/services:branch:staging"
      command:
        - "/bin/bash"
        - "-c"
        - "nix-env -iA nixpkgs.curl && mkdir /app && cd /app && curl -L https://github.com/mozilla-releng/services/archive/$GITHUB_HEAD_SHA.tar.gz -o $GITHUB_HEAD_SHA.tar.gz && tar zxf $GITHUB_HEAD_SHA.tar.gz && cd services-$GITHUB_HEAD_SHA && env && nix-shell nix/taskcluster.nix --pure --argstr taskcluster_secrets $TASKCLUSTER_SECRETS"
