---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Code Coverage"
consumes:
  - application/json
produces:
  - application/json
paths:
  /coverage/file:
    get:
      operationId: "codecoverage_backend.api.coverage_for_file"
      parameters:
      - name: changeset
        in: query
        description: Changeset
        required: true
        type: string
      - name: path
        in: query
        description: File
        required: true
        type: string
      responses:
        200:
          description: Code coverage information for a given file at a given changeset
      tags:
        - legacy

  /coverage/changeset/{changeset}:
    get:
      operationId: "codecoverage_backend.api.coverage_by_changeset"
      parameters:
      - name: changeset
        in: path
        description: Changeset
        required: true
        type: string
      responses:
        200:
          description: Code coverage information by changeset
      tags:
        - legacy

  /coverage/changeset_summary/{changeset}:
    get:
      operationId: "codecoverage_backend.api.coverage_summary_by_changeset"
      parameters:
      - name: changeset
        in: path
        description: Changeset
        required: true
        type: string
      responses:
        200:
          description: Code coverage summary by changeset
      tags:
        - legacy

  /coverage/supported_extensions:
    get:
      operationId: "codecoverage_backend.api.coverage_supported_extensions"
      responses:
        200:
          description: File extensions supported for code coverage
      tags:
        - legacy

  /coverage/latest:
    get:
      operationId: "codecoverage_backend.api.coverage_latest"
      responses:
        200:
          description: Latest coverage builds
      tags:
        - legacy

  /v2/latest:
    get:
      operationId: "codecoverage_backend.v2.coverage_latest"
      parameters:
      - name: repository
        in: query
        description: Mozilla repository for these reports (default to mozilla-central)
        required: false
        type: string
      responses:
        200:
          description: Latest coverage builds
      tags:
        - v2

  /v2/path:
    get:
      operationId: "codecoverage_backend.v2.coverage_for_path"
      parameters:
      - name: changeset
        in: query
        description: Changeset
        required: false
        type: string
      - name: path
        in: query
        description: File
        required: false
        type: string
      - name: repository
        in: query
        description: Mozilla repository for this changeset (default to mozilla-central)
        required: false
        type: string
      responses:
        200:
          description: Code coverage information for a given file or directory at a given changeset
      tags:
        - v2

  /v2/history:
    get:
      operationId: "codecoverage_backend.v2.coverage_history"
      parameters:
      - name: repository
        in: query
        description: Mozilla repository for these reports (default to mozilla-central)
        required: false
        type: string
      - name: start
        in: query
        description: Start timestamp for the history date range (default to a year before end)
        required: false
        type: string
      - name: end
        in: query
        description: End timestamp for the history date range (default to current timestamp)
        required: false
        type: string
      - name: path
        in: query
        description: Path of the repository folder to get coverage info on.
        required: false
        type: string
      responses:
        200:
          description: Overall coverage of specified path over a period of time
      tags:
        - v2
