checks:
  - cmd: flake8
    name: 'Checking code quality'
  - cmd: 'pytest tests/'
    name: 'Running tests'
deploy: HEROKU
deploy_options:
  production:
    dns: policy.notification.mozilla-releng.net.herokudns.com
    heroku_app: releng-production-notif-policy
    heroku_dyno_type: web
    url: https://policy.notification.mozilla-releng.net
  staging:
    dns: policy.notification.staging.mozilla-releng.net.herokudns.com
    heroku_app: releng-staging-notif-policy
    heroku_dyno_type: web
    url: https://policy.notification.staging.mozilla-releng.net
  testing:
    dns: policy.notification.testing.mozilla-releng.net.herokudns.com
    heroku_app: releng-testing-notif-policy
    heroku_dyno_type: web
    url: https://policy.notification.testing.mozilla-releng.net
requires:
  - postgresql
run: FLASK
run_options:
  port: 8006
