---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Signoff service"
consumes:
  - application/json
produces:
  - application/json
paths:

  /login:
    get:
      operationId: "shipit_signoff.api.login"
      description: Interactively log a user in
      parameters:
        - name: callback_url
          in: query
          description: Where to send the user in the UI after login
          required: true
          type: string
      responses:
        "302":
          description: Log a user in
        "307":
          description: Log a user in

# Useful for policy checking before step creation?
#  /validate_policy:
#    put:
#      operationId: "validate_policy"
#      description: Checks whether a given policy is valid and completable. 
#      parameters:
#        - name: policy
#          description: The policy to validate
#          in: body
#          required: true
#          type: string
#      responses:
#        200:
#          description: Returns nothing
#        422:
#          description: Unprocessable Entity


  /step:
    get:
      operationId: "shipit_signoff.api.list_steps"
      description: List all steps with status
      responses:
        "200":
          description: List of all steps
          schema:
            type: array
            items:
              $ref: '#/definitions/StepResult'


  /step/{uid}/status:

    get:
      operationId: "shipit_signoff.api.get_step_status"
      description: Status of a step
      parameters:
        - $ref: "#/parameters/uid"
      responses:
        "200":
          description: Status of a step
          schema:
            $ref: '#/definitions/StepResult'


  /step/{uid}:
    put:
      operationId: "shipit_signoff.api.create_step"
      description: Create new step
      parameters:
        - $ref: '#/parameters/uid'
        - name: definition
          in: body
          description: Step Definition
          required: true
          schema:
            $ref: '#/definitions/Step'
      responses:
        "200":
          description: Returns nothing

    delete:
      operationId: "shipit_signoff.api.delete_step"
      description: Remove a step
      parameters:
        - $ref: '#/parameters/uid'
      responses:
        "200":
          description: Removal of step
          
    get:
      operationId: "shipit_signoff.api.get_step"
      description: Step definition
      parameters:
          - $ref: '#/parameters/uid'
      responses:
        "200":
          description: Definition of step
          schema:
            $ref: '#/definitions/Step'


  # Signoff specific
  # User is acquired from the access token
  # Do we want the user to claim a specific group?
  /step/{uid}/sign:
    put:
      operationId: "shipit_signoff.api.sign_off"
      description: "Sign off"
      parameters:
        - $ref: '#/parameters/uid'
      responses:
        "200":
          description: signed off

  /step/{uid}/unsign:
    put:
      operationId: "shipit_signoff.api.delete_signature"
      description: "Remove a signature from a step"
      parameters:
        - $ref: '#/parameters/uid'
      responses:
        "200":
          description: Signature removed



definitions:

  StepResult:
    type: object
    required:
      - state
    properties:
      state:
        type: string
        enum:
          - starting # / pending
          - running
          - stopping
          - exception
          - completed #/ success
          - failed
      message:
        type: string
        description: More elaborate description of state for humans.
      signees:
        type: array
        description: A list of the users who have signed off this step
        items:
          type: string
      output:
        $ref: '#/definitions/Output'

#  StepList:
#    type: object
#    properties:
#      result:
#        type: array
#        description: A list of step statuses
#        uniqueItems: false
#        items:
#          - $ref: '#/definitions/StepResult'

  Step:
    type: object
    required:
      - uid
      - input
      - parameters
    properties:
      uid:
        type: string
      input:
        $ref: '#/definitions/Input'
      parameters:
        $ref: '#/definitions/Parameters'

  Parameters:
    type: object

  Input:
    type: object

  Output:
    type: object

parameters:
    uid:
        name: uid
        in: path
        description: Step UID
        required: true
        type: string
  
